# https://taskfile.dev

version: '3'

vars:
  VERSION_NUMBER:
      sh: git show-ref --tags | wc -l
  VERSION: v0.0.{{ .VERSION_NUMBER }}

tasks:
  build:
    description: build a local binary
    cmds:
      - go build -o bin/geid -ldflags="-s -w -X github.com/jxlxx/geid.Version={{.VERSION}}"

  release:
    cmds:
      - goreleaser release --clean
  tag:
    cmds:
      - git push
      - git tag {{ .VERSION }}
      - git push origin {{ .VERSION }}
  test-release:
    cmds:
      - goreleaser release --snapshot --clean
